### ISSUE TITLE
Gibberish subtitles 

### ISSUE THREAD

**Issue by Filipdarylxuh** [maormagori/ktuvit-stremio#37]
היי, רציתי לציין שישנם כתוביות אשר מופיעות בג'יבריש. לדוגמא:
בסרט הפייבלמנים
הדבר נבדק גם בקודי, ושם זה עובד הכל בסדר.

**Comment by TwilightMercy** [comment]
היי מאור, מקבוצת Stremio Israel כאן : )
מחזק את דבריו, שלושת הכתוביות הבאות של "הפייבלמנים" בקודי תקינות:
![image](https://user-images.githubusercontent.com/29895680/235372258-311d3ea3-4635-4c89-bb8a-0d1f69d845ec.png)


בסטרמיו 2 מהן באותיות ג'יבריש מוזרות:

![image](https://user-images.githubusercontent.com/29895680/235372397-24df6bb6-f239-46ae-99ae-9a820a4342c2.png)

**Comment by maormagori** [comment]
תודה @Filipdarylxuh, @TwilightMercy על העדכון!

הבעיה נגרמת בעקבות הקידודים השונים שבהם Ktuvit שומרת את קבצי הכתוביות שכנראה מגיעים ממקורות שונים.
עד כה שיערתי שכל הקבצים יעבדו עם הקידוד ISO-8859-8 אבל נראה שזה לא המצב.
שחררתי [גרסה חדשה של Ktuvit-api](https://github.com/maormagori/Ktuvit-api) שמנסה לזהות את הקידוד המתאים לקובץ לפני שהיא אוכפת אותו.
עדכנתי את ההרחבה לגרסא 0.1.2 שמשתמשת בגרסה החדשה של ktuvit-api.
סוגר לבינתיים את ה-issue, במידה והבעיה ממשיכה, מוזמנים לפתוח מחדש.

**Comment by maormagori** [comment]
A fix to the encoding problem was introduced in version [0.4.0 of ktuvit-api](https://github.com/maormagori/Ktuvit-api/pull/10).
Updated addon to 0.1.2 which uses version 0.4.0 of Ktuvit-api.

**Comment by maormagori** [comment]
נראה שהתיקון יוצר בעיה חדשה 🙃
שחזרתי את המצב הקודם לבינתיים ופותח מחדש את הבעיה עד שאבין מה גורם לכשל בעדכון.

**Comment by TwilightMercy** [comment]
נתעדכן פה כשיהיה חדש, תודה רבה על התמיכה!

**Comment by maormagori** [comment]
Trying again with #40
I'll keep an eye on it for now.

**Comment by maormagori** [comment]
נראה שהפתרון החדש יציב.
סוגר את ה-issue לבינתיים. מוזמנים לפתוח מחדש אם אתם עדיין נתקלים בבעיה.

**Comment by TwilightMercy** [comment]
עובד תקין תודה רבה!

**Comment by Filipdarylxuh** [comment]
תודה רבה מאור!
