### ISSUE TITLE
How do I add credentials if there's no config on the addon?

### ISSUE THREAD

**Issue by SubEdict** [maormagori/ktuvit-stremio#52]
Started using Stremio now that it run on Samsung TV (Tizen OS).
I already have user name/password (copy/past console code thingy), but there's no setting to fill in.
How does it supposed to work?

**Comment by TwilightMercy** [comment]
No need, the credentials are already filled in in addon’s code.

**Comment by SubEdict** [comment]
@TwilightMercy Oh wow, thanks for the fast info. 👍
